language: python
dist: trusty
sudo: required
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
 - pip install .
# command to run tests
script: make && for f in tests/*.py; do echo sudo "$f" && sudo "$f"; done
